### ISSUE TITLE
UI Mockup & Future Tasks

### ISSUE THREAD

**Issue by satrio-pamungkas** [Asadaaaaa/Kompetegram-Website#4]
### Intro
**Halo**, pertama-tama mau ngasih apresiasi sudah ngasih kontribusi ke Kompetegram dengan mengembangkan Website pakai React Js. Tapi sayang banget perihal ini belum diinfokan ke anggota-anggota lain, termasuk saya juga jadinya baru tau ada proyek pengembangan ini :laughing: (iseng - iseng ketemu di Feed)

### Pertanyaan
Nah berkaitan itu ada beberapa pertanyaan yang mau ditanyakan nih : 
1. Kalau proyek ini iseng coba-coba aja atau emang bakal jadi proyek di Keanggotaan atau Kepengurusan ?
2. Kira-kira untuk **Desain Mockup** atau **User Story** (Kebutuhan fungsional) apakah ada ? Supaya bisa di transformasikan jadi bentuk *To-Do* atau *Task* buat Slicing ke dalam komponen komponen React. (Barangkali bisa ikut develop bareng-bareng membuka potensi kolaborasi) 

Nice work, keep going :+1: 
<hr>
CC : @Asadaaaaa @ValdiANS 
(Semoga muncul notifnya :smile: )

**Comment by ValdiANS** [comment]
> ### Intro
> **Halo**, pertama-tama mau ngasih apresiasi sudah ngasih kontribusi ke Kompetegram dengan mengembangkan Website pakai React Js. Tapi sayang banget perihal ini belum diinfokan ke anggota-anggota lain, termasuk saya juga jadinya baru tau ada proyek pengembangan ini 😆 (iseng - iseng ketemu di Feed)
> 
> ### Pertanyaan
> Nah berkaitan itu ada beberapa pertanyaan yang mau ditanyakan nih :
> 
> 1. Kalau proyek ini iseng coba-coba aja atau emang bakal jadi proyek di Keanggotaan atau Kepengurusan ?
> 2. Kira-kira untuk **Desain Mockup** atau **User Story** (Kebutuhan fungsional) apakah ada ? Supaya bisa di transformasikan jadi bentuk _To-Do_ atau _Task_ buat Slicing ke dalam komponen komponen React. (Barangkali bisa ikut develop bareng-bareng membuka potensi kolaborasi)
> 
> Nice work, keep going 👍
> 
> CC : @Asadaaaaa @ValdiANS (Semoga muncul notifnya 😄 )

Izin jawab kang:
1. Proyek landing page ini proyek keanggotaan/kepengurusan kang, jadi proyek dari divisi Technology Specialist.
2. Untuk desainnya ada kang, yang bikinnya divisi content specialist kang. Kalau akang mau liat desainnya ini linknya kang https://www.figma.com/file/ZzfON6EBR8p6iKnvp7p5pv/UI-Landing-Page?node-id=14%3A2

**Comment by satrio-pamungkas** [comment]
Oke sip, keliatannya sudah beres ya kalau diliat dengan mockup nya. Ada rencana kedepan ?

Oh ya kalau mau pakai domain .com itu pindahin aja ya domain arahnya ke URL yang baru (nanti bilang aja ke Naufal, soalnya ada di akun idcloudhost) - Nanti perpanjang lagi aja kalau gasalah oktober habis masa berlaku domainnya.

**Comment by ValdiANS** [comment]
Maaf kang baru bales, baru liat notifnya di email 😅. Untuk sekarang kita lagi nunggu info/instruksi lebih lanjut dari lead kang

**Comment by satrio-pamungkas** [comment]
Oke jangan sungkan buat follow up ya ke lead

**Comment by Asadaaaaa** [comment]
> Oke jangan sungkan buat follow up ya ke lead

Halo kang maaf baru bales. Mungkin udah dijawab semua sama kang valdi, nanti saya segera follow up lagi ke lead nya kang
